- name: AWS SNS - Publish Topic
  uses: nothingalike/sns-publish-topic@v1.7

- name: Publish SNS Topic
  uses: nothingalike/sns-publish-topic@v1.6
  with:
    MESSAGE: "message"
    TOPIC_ARN: "arn:aws:sns:[your region]:[your account id]:[your topic name]"
  env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
