name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.7
        with:
          MESSAGE: "MUKODJ"
          TOPIC_ARN: "arn:aws:sns:eu-west-1:442864304639:GitPushEvents.fifo"
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
